### ISSUE TITLE
SetValue for text fields clears field after setting

### ISSUE THREAD

**Issue by mVermaat** [mVermaat/Crm.Specflow#3]
Temporary fix already implemented until EasyRepro is fixed. See: https://github.com/Microsoft/EasyRepro/issues/375

**Comment by mVermaat** [comment]
Workaround implemeneted until this is fixed

**Comment by jlattimer** [comment]
Submitted [PR 481](https://github.com/microsoft/EasyRepro/pull/481) for EasyRepro to address this
