### ISSUE TITLE
Using UI for Testing and API for data setup in Same Test

### ISSUE THREAD

**Issue by mike9182** [mVermaat/Crm.Specflow#69]
I am trying to verify that the correct fields are visible on a form, but am having some trouble with record setup. Since the records are created via integration and have forms that are completely read-only, they cannot be created through the UI.

Is there a way to set up data through the API and then test the form field visibility using the UI as part of a single test? I reviewed the code and do not see a simple way to do this.

**Comment by mVermaat** [comment]
After the pull request is merged. You can use the tag 'PreferAPI' to run on the API if possible. See the [wiki](https://github.com/mVermaat/Crm.Specflow/wiki/Writing-Features#command-actions).
